# Generated by Django 5.0.1 on 2024-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(unique=True)),
                ('tel_number', models.CharField(max_length=20)),
                ('fio', models.CharField(max_length=100)),
                ('new_square', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('overall_sum', models.CharField(max_length=20)),
                ('paid', models.CharField(max_length=20)),
                ('doc_number', models.PositiveBigIntegerField(unique=True)),
                ('doc_image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name': "Ma'lumot",
                'verbose_name_plural': "Ma'lumotlar",
            },
        ),
    ]
