# Generated by Django 5.0.1 on 2024-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='section',
            field=models.PositiveIntegerField(),
        ),
    ]
