# Generated by Django 5.0.1 on 2024-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='doc_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
